version: 1.0.{build}
branches:
  only:
  - Mono
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
- cmd: nuget restore
build:
  project: Ketarin.csproj
  verbosity: minimal
after_build:
- cmd: 7z a Ketarin-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.dll %APPVEYOR_BUILD_FOLDER%\bin\Release\*.exe  %APPVEYOR_BUILD_FOLDER%\bin\Release\*.config %APPVEYOR_BUILD_FOLDER%\bin\Release\x86\SQLite.Interop.dll %APPVEYOR_BUILD_FOLDER%\Assemblies\DiffieHellman.dll
artifacts:
- path: Ketarin-%APPVEYOR_BUILD_VERSION%.zip
  name: Ketarin-%APPVEYOR_BUILD_VERSION%.zip
deploy:
- provider: GitHub
  release: Ketarin-%APPVEYOR_BUILD_VERSION%
  auth_token:
    secure: /e1bIobrUwT05baBOG8YBiBgQAQRpEP5XfMcnhKszh9+8ypAqAaGxh+WELR5ctJC
  repository: franc6/Ketarin
  artifact: Ketarin-%APPVEYOR_BUILD_VERSION%.zip
  prerelease: true